Add Serilog logging and hosting
xoofx/UnityNuGet pull request #62
Opened 2021-10-07 15:09 UTC by KuraiAndras

> The NuGet package needs to respect a few constraints in order to be listed in the curated list:
> - [X] Add a link to the NuGet package:
>  - https://www.nuget.org/packages/Serilog.Extensions.Hosting/4.2.0
> - [X] It must have non-preview versions (e.g 1.0.0 but not 1.0.0-preview.1)
> - [X] It must provide .NETStandard2.0 assemblies as part of its package
> - [X] The lowest version added must be the lowest .NETStandard2.0 version available
> - [X] The package has been tested with the Unity editor 
> - [X] The package has been tested with a Unity standalone player
>   - if the package is not compatible with standalone player, please add a comment to a Known issues section to the top level readme.md
> - [X] All package dependencies with .NETStandard 2.0 target must be added to the PR (respecting the same rules above)
>   - Note that if a future version of the package adds a new dependency, this dependency will have to be added manually as well

2021-11-01 21:39 UTC, nblumhardt commented
Should be good to go now 👍

2021-11-01 21:41 UTC, bdovaz commented
@nblumhardt UnityNuGet only allows NuGet package stable versions. I thought that you would publish a stable 3.1.0 version.

2021-11-01 21:46 UTC, bdovaz requested changes

2021-11-01 21:46 UTC, bdovaz commented on registry.json
> +    "version": "2.0.0"
Change to 3.1.0

2021-11-01 21:46 UTC, bdovaz commented
We need to create a PR to bump the hosting NuGet package version and depend on logging 3.1.0 to gully unblock this PR

2021-11-01 22:55 UTC, KuraiAndras commented
@bdovaz I have created #69 so that the logging extension can be used before the hosting package is done

2021-11-02 07:03 UTC, KuraiAndras commented
Once https://github.com/serilog/serilog-extensions-hosting/pull/55 is done, I can update the version of the Hosting package

2021-11-08 23:00 UTC, KuraiAndras commented
@xoofx  @bdovaz  In the meanwhile .NET 6 came, and I think `Microsoft.Extensions.Hosting 6.0.0`  relies on `Microsoft.Extensions.Features` which is a new package. I also added that, since the build was failing

2021-11-21 06:20 UTC, merged